### ISSUE TITLE
Thanks for the amazing Theme!

### ISSUE THREAD

**Issue by subatoiWolf** [SirMotte/FoundryVTT-Theme-Hearth#1]
I have been using your Theme and the supported modules and it’s working great!!!  One module I use often in my games is Item Piles by Wasp.  Is there anyway to fix the CSS so that module could be used?  It’s UI is pretty squashed.  Thanks again for this amazing module!!!!

**Comment by SirMotte** [comment]
Hey there, thanks a lot! I'm glad you enjoy it. I'm using item piles myself and will add support this weekend. Some UI issues are caused by Ernie's UI, but he's quick to fix those, I'll contact him.

Just for reference, how did you stumble upon the theme? I didn't advertise it up until now but for a single mention on discord.

**Comment by subatoiWolf** [comment]
I saw it on Foundry discord. Also I switched to Whistlers Wire modules and Build a bonus and it is incredibly good with Hearth!!!!

**Comment by SirMotte** [comment]
Nice, I'll have to take a look myself, maybe there are things to tweak ;).

**Comment by subatoiWolf** [comment]
The other thing I noticed is the charactermancer is difficult to see using your module with Plutonium

**Comment by SirMotte** [comment]
> 

Could you send some screenshots my way? I'm not entirely sure what you mean.
Also: I've updated some theme elements, most notably the chat. Still WIP, but a lot better now and fixed some css duplicates messing soem elements on the tidy 5e sheet up. Give it a whirl.

**Comment by SirMotte** [comment]
> The other thing I noticed is the charactermancer is difficult to see using your module with Plutonium

I have as added some tweaks to plutonium graphics. could you test if this also affects the charactermancer? I don't have access to the tool as I don't support Plutonium on Patreon (and won't do so because of the many issues regarding copyright and pirating surrounding this tool).

**Comment by SirMotte** [comment]
I deleted the comments referencing a certain module.

**Comment by SirMotte** [comment]
> I have been using your Theme and the supported modules and it’s working great!!! One module I use often in my games is Item Piles by Wasp. Is there anyway to fix the CSS so that module could be used? It’s UI is pretty squashed. Thanks again for this amazing module!!!!

Grab the Pre-Release of Ernies's Modern UI, this will fix the issue.
